name = "Robin2011_RepPackage"
uuid = "70c05c58-fe50-4b85-b0b7-78d2ea2ba413"
authors = ["Bo Jacobs Strom <bojs.13@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
